# Site settings
title: docs.dev-sec-ops.ru на русском языке

description: Изучаем лучшие практики DevSecOps

keywords: DevSecOps, SRE, Security, Linux, Docker, Kubernetes, Clouds, Git, FluxCD, ArgoCD

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://docs.dev-sec-ops.ru' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
